// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttestationGenerateResponse = { "type": "token", token: string, latencyMs: number | null, } | { "type": "failure", failureReason: string, failureDetail: string | null, latencyMs: number | null, };
