// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerStatusDetail } from "./McpServerStatusDetail";

export type ListMcpServerStatusParams = {
/**
 * Optional environment used to start executor-backed MCP servers for this
 * threadless status read. Omitted preserves the legacy default/local
 * runtime environment.
 */
environmentId?: string | null,
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null,
/**
 * Optional page size; defaults to a server-defined value.
 */
limit?: number | null,
/**
 * Controls how much MCP inventory data to fetch for each server.
 * Defaults to `Full` when omitted.
 */
detail?: McpServerStatusDetail | null, };
