// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";
import type { TurnError } from "./TurnError";
import type { TurnStatus } from "./TurnStatus";

export type ThreadHistoryItem = { turnId: string, item: ThreadItem, turnStatus: TurnStatus, turnError: TurnError | null,
/**
 * Unix timestamp (in seconds) when the turn started.
 */
turnStartedAt: number | null,
/**
 * Unix timestamp (in seconds) when the turn completed.
 */
turnCompletedAt: number | null,
/**
 * Duration between turn start and completion in milliseconds, if known.
 */
turnDurationMs: number | null, };
