/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum UsageLimitNudgeState {
    Inactive,
    Active {
        #[serde(rename = "key")]
        key: String,
        #[serde(rename = "threshold")]
        threshold: u8,
        #[serde(rename = "action")]
        action: UsageLimitNudgeAction,
    },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageLimitNudgeAction {
    #[serde(rename = "add_credits")]
    AddCredits,
    #[serde(rename = "upgrade")]
    Upgrade,
}
